# Workflow name
name: Build and Publish to GitHub Pages

on:
    push:
        branches: [$default-branch] # Runs on pushes targeting the default branch

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# List of jobs
jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.build-publish.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v4

            # Set up Node
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install and Build
              run: |
                npm install
                npm run build
